name: Check GitHub Releases

on:
  schedule:
    - cron: "0 */6 * * *"        # Every 6 hours
    - cron: "0 6 * * *"          # Daily at 6 AM UTC
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run release checker
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: python github_release_to_discord.py
