name: FIA Scraper

# Trigger this workflow on every push or on a schedule (customize as needed)
on:
  schedule:
    # Every 5 minutes on Friday, Saturday, and Sunday (race weekend scanning)
    - cron: '*/5 * * * 5'
    - cron: '*/5 * * * 6'
    - cron: '*/5 * * * 0'
    # Once daily at 09:00 UTC on Monday–Thursday (light check)
    - cron: '0 9 * * 1'
    - cron: '0 9 * * 2'
    - cron: '0 9 * * 3'
    - cron: '0 9 * * 4'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI
  push:
    paths:
      - "fia_scraper/**"
      - ".github/workflows/fia_scraper.yml"

jobs:
  scrape-and-notify:
    runs-on: ubuntu-24.04  # Use latest Ubuntu runner

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_ERROR_WEBHOOK_URL: ${{ secrets.DISCORD_ERROR_WEBHOOK_URL }}

    steps:
      # 🧹 Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🐍 Step 2: Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 📦 Step 3: Install dependencies from requirements.txt
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🧪 Step 4: Cache file support (to prevent reposting same PDFs)
      - name: Restore cache of processed documents
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: last_fia_doc_hash.txt  # The cache file storing hashed URLs
          key: fia-doc-cache-v1        # Key to identify the cache version

      # 🧠 Step 5: Run the scraper script
      - name: Run FIA scraper
        run: xvfb-run --auto-servernum python fia_scraper/scraper.py
        # Uses xvfb to enable headless browser rendering with Firefox + Selenium

      # 💾 Step 6: Save updated cache after new documents processed
      - name: Save updated cache
        if: always()  # Always attempt to update cache even if script fails
        uses: actions/cache/save@v4
        with:
          path: last_fia_doc_hash.txt
          key: fia-doc-cache-v1