name: FIA Document Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-24.04

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_ERROR_WEBHOOK_URL: ${{ secrets.DISCORD_ERROR_WEBHOOK_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox and Geckodriver (v139.0 / v0.36.0)
      run: |
        set -ex
    
        sudo apt update
        sudo apt install -y wget tar xauth xvfb \
          libdbus-glib-1-2 libgtk-3-0 libx11-xcb1 \
          libxcb-shm0 libxcb-dri3-0 libxrandr2 libnss3 \
          libasound2t64 libxss1 libxtst6 || true
    
        # Firefox 139.0 instead of 139.0.1 (to avoid broken link)
        wget https://ftp.mozilla.org/pub/firefox/releases/139.0/linux-x86_64/en-US/firefox-139.0.tar.bz2
        tar -xjf firefox-139.0.tar.bz2
        sudo mv firefox /opt/firefox139
        sudo ln -sf /opt/firefox139/firefox /usr/local/bin/firefox
    
        wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
        tar -xzf geckodriver-v0.36.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/
    
        echo "✅ Firefox: $(firefox --version)"
        echo "✅ Geckodriver: $(geckodriver --version)"

    - name: Run FIA document scraper
      run: |
        xvfb-run --auto-servernum python fia_scraper/scraper.py
