name: FIA Document Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-24.04

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_ERROR_WEBHOOK_URL: ${{ secrets.DISCORD_ERROR_WEBHOOK_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox and Geckodriver
      run: |
        sudo apt update
        sudo apt install -y firefox
        FIREFOX_VERSION=$(firefox --version)
        echo "Installed Firefox: $FIREFOX_VERSION"
        
        FIREFOX_MAJOR=$(firefox --version | grep -oP '\d+' | head -1)
        GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases | jq -r '.[].tag_name' | grep -E "^v$FIREFOX_MAJOR" | head -1)
        echo "Installing Geckodriver $GECKO_VERSION for Firefox $FIREFOX_MAJOR"
        
        wget -q https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz
        tar -xzf geckodriver-*.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Run scraper
      run: python fia_scraper/scraper.py
