name: FIA Scraper

on:
  schedule:
    # Every 5 minutes on Friday, Saturday, and Sunday (race weekend scanning)
    - cron: '*/5 * * * 5'
    - cron: '*/5 * * * 6'
    - cron: '*/5 * * * 0'
    # Once daily at 09:00 UTC on Monday–Thursday (light check)
    - cron: '0 9 * * 1'
    - cron: '0 9 * * 2'
    - cron: '0 9 * * 3'
    - cron: '0 9 * * 4'

  workflow_dispatch:
    inputs:
      force:
        description: "Force run regardless of race weekend"
        required: false
        default: "false"

  push:
    paths:
      - "fia_scraper/**"
      - ".github/workflows/fia_scraper.yml"

jobs:
  scrape-and-notify:
    runs-on: ubuntu-24.04

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_ERROR_WEBHOOK_URL: ${{ secrets.DISCORD_ERROR_WEBHOOK_URL }}

    steps:
      # 🧹 Step 1: Clone the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🐍 Step 2: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 📦 Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🧪 Step 4: Restore cache of processed documents
      - name: Restore document hash cache
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: last_fia_doc_hash.txt
          key: fia-doc-cache-v1

      # 🧠 Step 5: Run the scraper script with optional --force if manually triggered
      - name: Run FIA scraper
        run: |
          FORCE_INPUT="${{ github.event.inputs.force || 'false' }}"
          FORCE_FLAG=""
          if [[ "$FORCE_INPUT" == "true" ]]; then
            FORCE_FLAG="--force"
          fi
          xvfb-run --auto-servernum python fia_scraper/scraper.py $FORCE_FLAG

      # 💾 Step 6: Save updated document hash cache
      - name: Save updated cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: last_fia_doc_hash.txt
          key: fia-doc-cache-v1
