name: FIA Document Scraper

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-24.04

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_ERROR_WEBHOOK_URL: ${{ secrets.DISCORD_ERROR_WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdbus-glib-1-2 \
            libgtk-3-0 \
            libx11-xcb1 \
            libxcb-shm0 \
            libxcb-dri3-0 \
            libxrandr2 \
            libnss3 \
            libasound2 \
            libxss1 \
            libxtst6 \
            xauth \
            xvfb

      - name: Install Firefox 127 and Geckodriver 0.36.0
        run: |
          wget -q https://ftp.mozilla.org/pub/firefox/releases/127.0/linux-x86_64/en-US/firefox-127.0.tar.bz2
          tar -xjf firefox-127.0.tar.bz2
          sudo mv firefox /opt/firefox127
          sudo ln -sf /opt/firefox127/firefox /usr/local/bin/firefox
          echo "Installed Firefox version: $(firefox --version)"

          wget -q https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xzf geckodriver-v0.36.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python fia_scraper/scraper.py
