name: Check FIA F1 Documents

on:
  schedule:
    - cron: "0 6 * * *"        # Once daily at 6 AM UTC (non-race days)
    - cron: "*/15 * * * *"     # Every 15 minutes (race days)
  workflow_dispatch:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run checker script
        env:
          F1_DOCS_WEBHOOK: ${{ secrets.F1_DOCS_WEBHOOK }}
        run: python fia_docs_to_discord.py
